Prodsetting av DMx og IAPIA
navikt/dvh-sykefravar-dmx pull request #9
Opened 2022-08-31 08:47 UTC by stigmhenriksen

2022-08-31 10:12 UTC, stigmhenriksen reviewed
fjerne print av bruker etc - debug kommandoer

2022-08-31 13:24 UTC, patped requested changes

2022-08-31 13:24 UTC, patped commented on dbt_project.yml
> +      +tags: syfra | IA_PIA
Fjern tag

2022-08-31 13:24 UTC, patped commented on models/dvh_syfo/forkammer/dim/stg_dim_diagnose.sql
> +) }}
Kan fjernes

2022-08-31 13:24 UTC, patped commented on models/dvh_syfo/forkammer/dim/stg_dim_geografi.sql
> +) }}
Kan fjernes

2022-08-31 13:24 UTC, patped commented on models/dvh_syfo/forkammer/dim/stg_dim_tid.sql
> +) }}
Kan fjernes

2022-08-31 13:24 UTC, patped commented on models/dvh_syfo/schema.yml
> +    tags: ['syfo','IA_PIA']
Tag kan fjernes

2022-08-31 13:24 UTC, patped commented on models/sykm/dim/stg_arbeidsperiode.sql
> +
Legg til IA-PIA tag hvis den skal kjøres med resten av IA PIA

2022-08-31 13:24 UTC, patped commented on models/sykm/forkammer/stg_fak_sykm_sykefravar_tilfelle.sql
> +    where  extract(year from sykefravar_fra_dato) = 2022
Fikse dato filtrering

2022-08-31 13:24 UTC, patped commented on setup_db_user.ps1
> -$env:DBT_DB_PASS = $creds.GetNetworkCredential().password
Endre tilbake til DBT_DB_PASS

2022-09-01 05:56 UTC, stigmhenriksen commented on dbt_project.yml
> +      +tags: syfra | IA_PIA
done

2022-09-01 05:56 UTC, stigmhenriksen commented on models/dvh_syfo/forkammer/dim/stg_dim_diagnose.sql
> +) }}
done

2022-09-01 05:56 UTC, stigmhenriksen commented on models/dvh_syfo/forkammer/dim/stg_dim_geografi.sql
> +) }}
done

2022-09-01 05:56 UTC, stigmhenriksen commented on models/dvh_syfo/forkammer/dim/stg_dim_tid.sql
> +) }}
done

2022-09-01 05:56 UTC, stigmhenriksen commented on models/dvh_syfo/schema.yml
> +    tags: ['syfo','IA_PIA']
done

2022-09-01 05:57 UTC, stigmhenriksen commented on models/sykm/dim/stg_arbeidsperiode.sql
> +
done

2022-09-01 05:57 UTC, stigmhenriksen commented on models/sykm/forkammer/stg_fak_sykm_sykefravar_tilfelle.sql
> +    where  extract(year from sykefravar_fra_dato) = 2022
done

2022-09-01 05:57 UTC, stigmhenriksen commented on setup_db_user.ps1
> -$env:DBT_DB_PASS = $creds.GetNetworkCredential().password
done

2022-09-01 05:57 UTC, merged